Address all FIgma comments and UI text changes in Figma files for login, join, waitlist and add logic for waitlist env variable
find-labs/find pull request #10
Opened 2022-08-18 02:27 UTC by Excellent-coding

https://linear.app/find-labs/issue/ENG-26/address-all-figma-comments-and-ui-text-changes-in-figma-files-for

- Connect Payment
- Header, Footer, Auth links
- Text and UI update

2022-08-19 13:41 UTC, khalil-omer requested changes

2022-08-19 13:41 UTC, khalil-omer commented on apps/web-app/src/components/CheckoutForm.tsx
> +    e.preventDefault();
@Excellent-coding don't we need to handle submit?

2022-08-19 13:41 UTC, khalil-omer commented on apps/web-app/src/pages/connect-payment.tsx
> +const stripePromise = loadStripe('pk_live_Qr3xcCMK3oQ9rs1GRDmsxVyf004BexykCf');
This key should load from an env.

2022-08-19 13:41 UTC, khalil-omer commented on apps/web-app/src/pages/connect-payment.tsx
> +          <li className="flex my-3 text-gray-500"><div className="w-4 h-4 rounded-full bg-gray-400 my-auto mr-2" />Sed posuere liqula a nulla sagittis, et consectetur.</li>
@Excellent-coding  I think you are using the _wireframe_ tab in Figma. Don't use that tab. Use the **desktop** tab which has all of the correct text.

2022-08-20 05:32 UTC, Excellent-coding commented on apps/web-app/src/components/CheckoutForm.tsx
> +    e.preventDefault();
Now this is only design for now
I will integrate stripe at ENG-30 card

2022-08-20 20:06 UTC, khalil-omer requested changes
Don't use the wireframe tab of the Figma file. Use 'UI Desktop'

2022-08-20 20:06 UTC, khalil-omer commented on apps/web-app/src/pages/waitlist.tsx
>        <Button
Button color wrong

2022-08-20 20:06 UTC, khalil-omer commented on apps/web-app/src/pages/waitlist.tsx
> +          <Input
Input bg color wrong.

2022-08-21 22:32 UTC, Excellent-coding commented on apps/web-app/src/pages/waitlist.tsx
> +          <Input
I think now dark mode has same colors, so I will work on dark-mode branch(eng-32) and will create a PR for this ticket
Let's close this PR, I will create new PR based on the ENG-32 branch

2022-08-21 22:35 UTC, khalil-omer requested changes
Conflicts

2022-08-24 19:13 UTC, closed without merging