Add dark mode to login/join/waitlist screens (see designs - based on system preference)
find-labs/find pull request #12
Opened 2022-08-20 13:41 UTC by Excellent-coding

https://linear.app/find-labs/issue/ENG-32/add-dark-mode-to-loginjoinwaitlist-screens-see-designs-based-on-system

2022-08-20 18:22 UTC, khalil-omer requested changes
This is supposed to be based on system setting,

2022-08-20 18:22 UTC, khalil-omer commented on apps/web-app/src/components/ThemeSelectButton.tsx
> +import { MoonIcon, SunIcon } from "@radix-ui/react-icons";
This component is not in the designs. We might use it in the future, but it should not be added to the auth pages.

2022-08-20 18:22 UTC, khalil-omer commented on apps/web-app/src/components/Navbar.tsx
> +        <ThemeSelectButton />
You can create this component for the future, but it is not part of the designs right now so we should not add the ThemeSelectButton to any pages.

2022-08-21 21:04 UTC, Excellent-coding commented on apps/web-app/src/components/ThemeSelectButton.tsx
> +import { MoonIcon, SunIcon } from "@radix-ui/react-icons";
got it

2022-08-21 22:20 UTC, khalil-omer approved these changes

2022-08-21 22:20 UTC, merged