Logo should be svg, not text
find-labs/find pull request #23
Opened 2022-08-26 01:03 UTC by Excellent-coding

https://linear.app/find-labs/issue/ENG-29/logo-should-be-svg-not-text

2022-08-26 16:44 UTC, khalil-omer requested changes

2022-08-26 16:44 UTC, khalil-omer commented on apps/web-app/src/components/Navbar.tsx
>          <div className="flex cursor-pointer">
This div is not horizontally centered properly. It is not aligned with the rest of the page https://share.cleanshot.com/4H4CugXWDml95sHih3vp

2022-08-26 16:44 UTC, khalil-omer commented on apps/web-app/src/components/Navbar.tsx
> +            src={theme === "dark" ? "/find-logo-white.svg" : "/find-logo.svg"}
This Image tag looks correct, however as you can see it is not working: https://share.cleanshot.com/Mjfmaah8gYsx88wyApAR

2022-08-26 20:54 UTC, Excellent-coding commented on apps/web-app/src/components/Navbar.tsx
>          <div className="flex cursor-pointer">
got it

2022-08-26 20:55 UTC, Excellent-coding commented on apps/web-app/src/components/Navbar.tsx
> +            src={theme === "dark" ? "/find-logo-white.svg" : "/find-logo.svg"}
got it

2022-08-27 00:29 UTC, khalil-omer commented on apps/web-app/src/components/Navbar.tsx
> +            src={theme === "dark" ? "/find-logo-white.svg" : "/find-logo.svg"}
@Excellent-coding I am still seeing this issue.

2022-08-27 00:29 UTC, khalil-omer commented on apps/web-app/src/components/Navbar.tsx
>          <div className="flex cursor-pointer">
@Excellent-coding I am still seeing this issue

2022-08-31 17:03 UTC, khalil-omer requested changes
Issues are still happening (see comments)

2022-08-31 20:35 UTC, Excellent-coding commented on apps/web-app/src/components/Navbar.tsx
> +            src={theme === "dark" ? "/find-logo-white.svg" : "/find-logo.svg"}
https://prnt.sc/NlGAJAW-7KTo
Its really wired
This is my screen and everything is working as expected
I think this is related with cache, would you please clear your cache on your browser?

2022-08-31 20:35 UTC, Excellent-coding commented on apps/web-app/src/components/Navbar.tsx
>          <div className="flex cursor-pointer">
https://prnt.sc/NlGAJAW-7KTo
Its really wired
This is my screen and everything is working as expected
I think this is related with cache, would you please clear your cache on your browser?

2022-09-01 01:08 UTC, khalil-omer approved these changes

2022-09-01 01:09 UTC, khalil-omer commented
@Excellent-coding I still see the issues even on a different computer, but I am merging anyway and maybe we can debug once merged.

2022-09-01 01:09 UTC, merged