https://linear.app/find-labs/issue/ENG-59/findlabsorg-coming-soon-landing-page
find-labs/find pull request #43
Opened 2022-10-17 18:56 UTC by Excellent-coding

2022-10-17 22:47 UTC, khalil-omer requested changes

2022-10-17 22:47 UTC, khalil-omer commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
Why do we need next-auth in the marketing site?

2022-10-17 22:47 UTC, khalil-omer commented on apps/find-labs-org/src/pages/index.tsx
> +  if (process.env.NEXT_PUBLIC_IS_WAITLIST == 'true')
This env should be used at build time, not run time, so we don't need `NEXT_PUBLIC_` prefix.

2022-10-17 22:47 UTC, khalil-omer commented on apps/find-labs-org/src/pages/index.tsx
> +  else
To make this index page simpler, I think you should use components. <ComingSoon> and <FullHomePage> Then you can just do

```
 if (process.env.NEXT_PUBLIC_IS_WAITLIST == 'true')
return (<ComingSoon/>);
else
```

2022-10-17 22:47 UTC, khalil-omer reviewed
Reminder to rename from find-labs-org to marketing-site

2022-10-17 22:47 UTC, khalil-omer commented on apps/find-labs-org/src/components/ThemeSelectButton.tsx
> +import { MoonIcon, SunIcon } from '@radix-ui/react-icons';
There is no theme select button in the design

2022-10-17 22:57 UTC, khalil-omer requested changes
There is a memory leak https://cln.sh/kfdIueuysxHEL3oYIQ5v

2022-10-19 19:35 UTC, khalil-omer commented
@Excellent-coding there is feedback here for you

2022-10-25 19:29 UTC, khalil-omer requested changes
Please check the Vercel preview link and you will see I have added 3 comments in Vercel.

2022-10-25 19:29 UTC, khalil-omer commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
@Excellent-coding we need to do something with the form submissions. Maybe add them to waitlist?

2022-10-26 17:15 UTC, Excellent-coding commented
> Reminder to rename from find-labs-org to marketing-site

Done

2022-10-26 17:35 UTC, Excellent-coding commented
> There is a memory leak https://cln.sh/kfdIueuysxHEL3oYIQ5v

Should be solved now

2022-10-26 18:30 UTC, khalil-omer commented
@Excellent-coding be sure to click on https://vercel.live/open-feedback/marketing-site-git-yaser-eng-54-build-findlabs-46b018-find-labs.vercel.app?nextHash=show-comment-archive%3Dtrue to see my Vercel comments.

2022-10-26 21:56 UTC, Excellent-coding commented
> 

Sent request for Vercel access

2022-10-27 01:50 UTC, Excellent-coding commented
> @Excellent-coding be sure to click on https://vercel.live/open-feedback/marketing-site-git-yaser-eng-54-build-findlabs-46b018-find-labs.vercel.app?nextHash=show-comment-archive%3Dtrue to see my Vercel comments.

All issues were resolevd

2022-10-27 02:32 UTC, khalil-omer commented on apps/find-labs-org/src/pages/index.tsx
> +  if (process.env.NEXT_PUBLIC_IS_WAITLIST == 'true')
@Excellent-coding

2022-10-27 02:32 UTC, khalil-omer commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
@Excellent-coding

2022-10-27 05:49 UTC, Excellent-coding commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
That's for later use in main page (not coming soon page)

2022-10-27 05:52 UTC, Excellent-coding commented on apps/find-labs-org/src/pages/index.tsx
> +  if (process.env.NEXT_PUBLIC_IS_WAITLIST == 'true')
ok, so should I follow env pattern used in web-app?

2022-10-27 15:15 UTC, khalil-omer commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
What will we use it for on main page?

2022-10-27 15:17 UTC, khalil-omer commented on apps/find-labs-org/src/pages/index.tsx
> +  if (process.env.NEXT_PUBLIC_IS_WAITLIST == 'true')
For marketing site, it can just be server-side env, so `NEXT_PUBLIC` isn't necessary

2022-10-27 21:05 UTC, Excellent-coding commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
authentication for user log in, I think

2022-10-27 21:19 UTC, khalil-omer commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
We won't have user login on marketing site I don't think

2022-10-27 21:54 UTC, Excellent-coding commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
That was designed in figma
https://prnt.sc/ZUb9djrWYlzN

2022-10-27 22:06 UTC, khalil-omer commented
That just redirects to https://find.new/login

On Thu, Oct 27, 2022 at 2:54 PM, Excellent Coding < ***@***.*** > wrote:

> 
> 
> 
> ***@***.**** commented on this pull request.
> 
> 
> 
> In apps/ find-labs-org/ src/ pages/ _app. tsx (
> https://github.com/find-labs/find/pull/43#discussion_r1007413230 ) :
> 
> > @@ -0,0 +1,25 @@
> +import type { AppProps } from 'next/app';
> +import Head
> from 'next/head';
> +import { SessionProvider } from 'next-auth/react';
> 
> 
> That was designed in figma
> https:/ / prnt. sc/ ZUb9djrWYlzN ( https://prnt.sc/ZUb9djrWYlzN )
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub (
> https://github.com/find-labs/find/pull/43#discussion_r1007413230 ) , or unsubscribe
> (
> https://github.com/notifications/unsubscribe-auth/AQIFNCM6X2WIWVQOIPB2SJ3WFL2Z3ANCNFSM6AAAAAARHLJTUU
> ).
> You are receiving this because you commented. Message ID: <find-labs/find/pull/43/review/1159089608
> @ github. com>
> 
> 
>

2022-10-28 01:42 UTC, Excellent-coding commented on apps/find-labs-org/src/pages/index.tsx
> +  if (process.env.NEXT_PUBLIC_IS_WAITLIST == 'true')
The env file should be updated

2022-10-28 15:20 UTC, khalil-omer commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
@Excellent-coding  That button just redirects to https://find.new/login

2022-10-28 16:50 UTC, Excellent-coding commented on apps/find-labs-org/src/pages/_app.tsx
> +import { SessionProvider } from 'next-auth/react';
ok, got it

2022-10-28 17:04 UTC, Excellent-coding commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
maybe redirecting to https://find.new/waitlist ?

2022-10-28 17:12 UTC, khalil-omer commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
@Excellent-coding Actually I think we should call the existing API route and just add them to the waitlist.

2022-10-28 17:14 UTC, Excellent-coding commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
ok, got it

2022-10-28 17:54 UTC, Excellent-coding commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
after form submission, should it be redirected to https://find.new/waitlist-success ?

2022-10-28 17:55 UTC, khalil-omer commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
Good idea.

2022-10-28 19:14 UTC, Excellent-coding commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
I tried to call the corresponding API route, but not getting success. 
https://prnt.sc/VNZHDmyKMcpl
In this case, is it right if I go for implementing email submission part implicitly ?

2022-10-28 21:48 UTC, khalil-omer commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
@Excellent-coding "implicitly" what do you mean?

2022-10-28 21:52 UTC, Excellent-coding commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
I mean, as a new email provider for marketing site, independent from web app email handler

2022-10-28 22:53 UTC, khalil-omer commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
@Excellent-coding maybe instead of trying to call the API route through trpc, you just create a new api route in web-app that is a normal POST route, and then call the trpc resolver function from there. Then you can simply call that new API route from marketing-site without interacting with trpc

2022-11-05 19:51 UTC, Excellent-coding commented on apps/find-labs-org/src/components/ComingSoon.tsx
> +          <form method='post'>
I implemented new API route and redirection to https://find.new/waitlist-success.
So by all means, this workflow is same as https://find.new/waitlist.
Please confirm if this is correct so I can push.

2022-11-07 16:51 UTC, khalil-omer approved these changes
All the code is looking good for coming soon. Just need to address the Vercel comments.

2022-11-07 19:23 UTC, merged