Build join screens and routes
find-labs/find pull request #6
Opened 2022-08-11 02:06 UTC by Excellent-coding

https://linear.app/find-labs/issue/ENG-16/build-join-screens-and-routes

Password checker
Auth navbar link
Social login optional view

2022-08-12 00:01 UTC, khalil-omer requested changes
NEXT_PUBLIC exposes the envs to the browser. That would be a major security issue. We just need these envs at build time, not request time.

2022-08-12 03:03 UTC, Excellent-coding commented
On a frontend side, we should display social login buttons
So if the client id is not defined, then it doesn't show it
So I just add NEXT_PUBLIC for client id keys

Still secret key is invisible
Would you please let me know your thoughts

2022-08-12 14:43 UTC, khalil-omer commented
Can’t we calculate that at build time rather than client side at run time?

On Thu, Aug 11 2022 at 8:03 PM, Excellent Coding < ***@***.*** > wrote:

> 
> 
> 
> 
> 
> 
> 
> On a frontend side, we should display social login buttons
> So if the client id is not defined, then it doesn't show it
> So I just add NEXT_PUBLIC for client id keys
> 
> 
> 
> Still secret key is invisible
> Would you please let me know your thoughts
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub (
> https://github.com/find-labs/find/pull/6#issuecomment-1212683846 ) , or unsubscribe
> (
> https://github.com/notifications/unsubscribe-auth/AQIFNCO5V6IOBW3ZT36Q32DVYW5ILANCNFSM56GRMYIA
> ).
> You are receiving this because your review was requested. Message ID: <find-labs/find/pull/6/c1212683846
> @ github. com>
> 
> 
>

2022-08-15 22:07 UTC, khalil-omer requested changes

2022-08-15 22:07 UTC, khalil-omer commented on apps/web-app/src/env/schema.mjs
> +  // NEXT_PUBLIC_BAR: process.env.NEXT_PUBLIC_BAR,
I think this can be removed. It can just be an empty object.

2022-08-15 22:07 UTC, khalil-omer commented on apps/web-app/src/components/PasswordChecker.tsx
> +    console.log({
Console.log should not be included

2022-08-15 22:07 UTC, khalil-omer commented on apps/web-app/src/pages/auth/create-password.tsx
> +        Your master password is the only wat to access your Find account. It&apos;s used to end-to-end encrypt your private data. Use a strong password and keep it a secret.
"way" not "wat"

2022-08-15 22:07 UTC, khalil-omer commented on apps/web-app/src/components/SocialLogin.tsx
>  };
I think that this https://share.cleanshot.com/lkP1JQynmz8J4mbEJTPz should be moved to this `SocialLogin.tsx` file. The reason is, if all social logins are missing an env, then we don't need to say "OR"

2022-08-16 20:48 UTC, khalil-omer approved these changes

2022-08-16 20:48 UTC, merged