Build waitlist screens and routes
find-labs/find pull request #7
Opened 2022-08-11 02:26 UTC by Excellent-coding

https://linear.app/find-labs/issue/ENG-17/build-waitlist-screens-and-routes

2022-08-11 23:54 UTC, khalil-omer requested changes

2022-08-11 23:54 UTC, khalil-omer commented on apps/web-app/src/pages/waitlist.tsx
>    const handleSubmit = () => {
This function should actually handle submit by calling a tRPC query. https://trpc.io/docs/react-queries

Then we also need to define that query in the Next.js backend via trpc. We can use Prisma to update the waitlist table.

2022-08-12 03:57 UTC, Excellent-coding commented
trpc waitlist table
waitlist create or update by email

2022-08-12 17:10 UTC, khalil-omer requested changes

2022-08-12 17:10 UTC, khalil-omer commented on apps/web-app/prisma/schema.prisma
> +model Waitlist {
We already discussed this schema. We don't need an id. We can just use email. And we need to know some other values.

```
model Waitlist {
    // Email address that wants to join Find
    email String @id
    // When user submitted the waitlist form
    createdAt DateTime @default(now())
    modifiedAt DateTime @updatedAt
    // If the waitlist entry has already been converted to a user.
    redeemed Boolean @default(false)
    // Whether to allow a user to join with the redemption secret
    allowRedeem Boolean @default(false)†
}
```

2022-08-13 13:30 UTC, Excellent-coding commented on apps/web-app/prisma/schema.prisma
> +model Waitlist {
yes, I will update the schema

2022-08-13 16:00 UTC, khalil-omer requested changes
Env

2022-08-13 16:00 UTC, khalil-omer commented on apps/web-app/prisma/schema.prisma
> +    url      = "postgres://postgres:mysecretpassword@localhost:5432/find"
This needs to stay an env. Revert this change please.

2022-08-16 21:15 UTC, khalil-omer approved these changes

2022-08-16 22:17 UTC, merged